title: Initial Commit
tagline: Listen, Learn.
email: wwwjfy@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.wwwjfy.net" # the base hostname & protocol for your site
author: Tony Wang
twitter_username: wwwjfy
github_username: wwwjfy

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

google_analytics_tracking_id: 'UA-21631590-1'
disqus_shortname: 'initialcommit'
