#!/bin/bash

title=$1
if [ -z "$title" ]; then
    echo "ERROR: Title is necessary"
    exit 1
fi
date=$(date "+%Y-%m-%d")
slug=$(echo "${title}" | awk '{gsub(/[: ]+/, "-"); print tolower($0)}')
path="_posts/${date}-${slug}.md"
{
    echo "---"
    echo "date: \"$(date "+%Y-%m-%d %H:%M:%S %z")\""
    echo "layout: post"
    echo "slug: \"${slug}\""
    echo "title: \"${title}\""
    echo "categories:"
    echo "- "
    echo "tags:"
    echo "- "
    echo "---"
    echo ""
} > "$path"
echo "new post generated as $path"
